### ISSUE TITLE
jss/utilities-fix-file-names.sh

### ISSUE THREAD

**Issue by kylejericson** [UoE-macOS/jss#18]
Can this script be easily updated for more folders to scan through? I want it to go through Desktop, Documents, Downloads, Movies, Music, and Pictures?

**Comment by dsavageED** [comment]
Yes it could, basically there are repeating lines (which should really be a function) to populate the list of files using the find command... Something like the Music folder could be an issue though, I'm not sure how well iTunes would take the name/path being changed. I might try and make the script a little more flexible in general.

find /Users/$uun/Documents -name "*" >> /tmp/cln.ffn
find /Users/$uun/Desktop -name "*" >> /tmp/cln.ffn
find "${onedrive}" -name "*" >> /tmp/cln.ffn
find /Users/$uun/Download -name "*" >> /tmp/cln.ffn
