### ISSUE TITLE
coreconfig-softwareupdate-run not working with 10.14.4

### ISSUE THREAD

**Issue by n0brainer** [UoE-macOS/jss#19]
I ran this on a 10.14.3 machine to update to 10.14.4. The script found and prompted for the update, but then just kind of hung there after it cached the download.  A force restart caused it to reboot to recovery partition saying the startup disk needed to update and awaited a prompt to continue.  After selecting continue it booted up again but wasn't on 10.14.4.  I ran the script again and this time it started the install...
Attached are the first run Jamf recorded log, the terminal output (I kicked off the policy manually), and the install.log output from the update.  The first run.txt file, @ 8:17 where the error is, was from when I finally gave up and hit ctrl-c to break out of the Jamf function.  The 2nd time running through terminal (after reboot) didn't upload any record to Jamf, so no log available to provide, but it did complete successfully. 

[softwareupdate deferral.log](https://github.com/UoE-macOS/jss/files/3013487/softwareupdate.deferral.log)

[cmd.log](https://github.com/UoE-macOS/jss/files/3013490/cmd.log)
[first run.txt](https://github.com/UoE-macOS/jss/files/3013492/first.run.txt)

**Comment by dsavageED** [comment]
Hi,

We have sort of gone back to basics with softwareupdate, since the script you mention had gotten bloated and unwieldy... The new script is here - https://github.com/UoE-macOS/jss/blob/master/software_update_2019

Cheers, David

**Comment by n0brainer** [comment]
Thanks, I just tried the 2019 and it prompts and shows the 10.14.4 update and allows deferrals and everything properly, but when I tell it to install it doesn't process the reboot, just stays on Installing required updates and Please wait...

**Comment by dsavageED** [comment]
Apologies,

Thats because we also took the opertunity to try authenticated reboots, via:

/usr/local/bin/jamf policy -event authenticated-restart

If you create a jamf policy with this custom trigger containing restart options it will work... Otherwise just change that line to:

osascript -e 'tell app "System Events" to restart'
