### ISSUE TITLE
software_update_2019 non restart updates

### ISSUE THREAD

**Issue by n0brainer** [UoE-macOS/jss#20]
I updated the script to the April 15th version and ran it on a machine that has a pending update for a recommended, non-restart update and the popup displays that the machine requires a restart and only provides Apply now as an option.
<img width="356" alt="Screen Shot 2019-04-18 at 10 33 26 AM" src="https://user-images.githubusercontent.com/2116991/56372855-6f950700-61c5-11e9-8607-bcee9cfc38ee.png">
<img width="232" alt="Screen Shot 2019-04-18 at 10 32 42 AM" src="https://user-images.githubusercontent.com/2116991/56372857-6f950700-61c5-11e9-83a2-b6d1c459a480.png">

**Comment by dsavageED** [comment]
Embarrassingly I had the conditions in this _if [[ "${Check_Defer_Limit}" > "${Today}" ]]; then_ the wrong way round, in a working copy that got used. The present version corrects this, though it also removes the network check
