### ISSUE TITLE
SALT Help

### ISSUE THREAD

**Issue by swilliams83** [UoE-macOS/jss#22]
Sorry, I'm new to this, any documentation/youtube etc. you can point me to in order to learn how to salt the username and password? Never used Salt before.  I think I understand how it works, and how to generate for a password, but not how to use it with your variables and generate it to pair a username with a password or encrypt both?

**Comment by dsavageED** [comment]
Hi, I haven't been on github in a while. If you still need some help with this have a look at - https://github.com/jamf/Encrypted-Script-Parameters
